# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Let's start with categories that don't have any children.

Category.find_or_create_by(name: 'Acai Bowls')
Category.find_or_create_by(name: 'Afghani')
Category.find_or_create_by(name: 'American (New)')
Category.find_or_create_by(name: 'American (Traditional)')
Category.find_or_create_by(name: 'Arabian')
Category.find_or_create_by(name: 'Argentine')
Category.find_or_create_by(name: 'Armenian')
Category.find_or_create_by(name: 'Asian Fusian')
Category.find_or_create_by(name: 'Australian')
Category.find_or_create_by(name: 'Austrian')
Category.find_or_create_by(name: 'Bagels')
Category.find_or_create_by(name: 'Bakeries')
Category.find_or_create_by(name: 'Bangladeshi')
Category.find_or_create_by(name: 'Barbeque')
Category.find_or_create_by(name: 'Basque')
Category.find_or_create_by(name: 'Beer Gardens')
Category.find_or_create_by(name: 'Belgian')
Category.find_or_create_by(name: 'Brasseries')
Category.find_or_create_by(name: 'Brazilian')
Category.find_or_create_by(name: 'Breakfast & Brunch')
Category.find_or_create_by(name: 'Breweries')
Category.find_or_create_by(name: 'British')
Category.find_or_create_by(name: 'Bubble Tea')
Category.find_or_create_by(name: 'Buffets')
Category.find_or_create_by(name: 'Burgers')
Category.find_or_create_by(name: 'Burmese')
Category.find_or_create_by(name: 'Cafeterias')
Category.find_or_create_by(name: 'Cajun/Creole')
Category.find_or_create_by(name: 'Cambodian')
Category.find_or_create_by(name: 'Catalan')
Category.find_or_create_by(name: 'Cheesesteaks')
Category.find_or_create_by(name: 'Chicken Shops')
Category.find_or_create_by(name: 'Chicken Wings')
Category.find_or_create_by(name: 'Chimney Cakes')
Category.find_or_create_by(name: 'Churros')
Category.find_or_create_by(name: 'Cideries')
Category.find_or_create_by(name: 'Coffee & Tea')
Category.find_or_create_by(name: 'Comfort Food')
Category.find_or_create_by(name: 'Creperies')
Category.find_or_create_by(name: 'Cuban')
Category.find_or_create_by(name: 'Cupcakes')
Category.find_or_create_by(name: 'Czech')
Category.find_or_create_by(name: 'Delis')
Category.find_or_create_by(name: 'Desserts')
Category.find_or_create_by(name: 'Diners')
Category.find_or_create_by(name: 'Dinner Theater')
Category.find_or_create_by(name: 'Distilleries')
Category.find_or_create_by(name: 'Do-It-Yourself Food')
Category.find_or_create_by(name: 'Donuts')
Category.find_or_create_by(name: 'Empanadas')
Category.find_or_create_by(name: 'Ethiopean')
Category.find_or_create_by(name: 'Fast Food')
Category.find_or_create_by(name: 'Filipino')
Category.find_or_create_by(name: 'Fish & Chips')
Category.find_or_create_by(name: 'Fondue')
Category.find_or_create_by(name: 'Food Courts')
Category.find_or_create_by(name: 'Food Stands')
Category.find_or_create_by(name: 'Food Trucks')
Category.find_or_create_by(name: 'Game Meat')
Category.find_or_create_by(name: 'Gastropubs')
Category.find_or_create_by(name: 'Gelato')
Category.find_or_create_by(name: 'German')
Category.find_or_create_by(name: 'Gluten-Free')
Category.find_or_create_by(name: 'Greek')
Category.find_or_create_by(name: 'Guamanian')
Category.find_or_create_by(name: 'Halal')
Category.find_or_create_by(name: 'Hawaiian')
Category.find_or_create_by(name: 'Himalayan/Nepalese')
Category.find_or_create_by(name: 'Honduran')
Category.find_or_create_by(name: 'Hong Kong Style Cafes')
Category.find_or_create_by(name: 'Hot Dogs')
Category.find_or_create_by(name: 'Hot Pot')
Category.find_or_create_by(name: 'Hungarian')
Category.find_or_create_by(name: 'Iberian')
Category.find_or_create_by(name: 'Ice Cream & Frozen Yogurt')
Category.find_or_create_by(name: 'Indian')
Category.find_or_create_by(name: 'Indonesian')
Category.find_or_create_by(name: 'Irish')
Category.find_or_create_by(name: 'Juice Bars & Smoothies')
Category.find_or_create_by(name: 'Kebab')
Category.find_or_create_by(name: 'Kombucha')
Category.find_or_create_by(name: 'Korean')
Category.find_or_create_by(name: 'Kosher')
Category.find_or_create_by(name: 'Laotian')
Category.find_or_create_by(name: 'Live/Raw Food')
Category.find_or_create_by(name: 'Malaysian')
Category.find_or_create_by(name: 'Modern European')
Category.find_or_create_by(name: 'Mongolian')
Category.find_or_create_by(name: 'Moroccan')
Category.find_or_create_by(name: 'New Mexican')
Category.find_or_create_by(name: 'New Zealand')
Category.find_or_create_by(name: 'Nicaraguan')
Category.find_or_create_by(name: 'Noodles')
Category.find_or_create_by(name: 'Pakistani')
Category.find_or_create_by(name: 'Pan Asian')
Category.find_or_create_by(name: 'Patisseries/Cake Shops')
Category.find_or_create_by(name: 'Persian/Iranian')
Category.find_or_create_by(name: 'Peruvian')
Category.find_or_create_by(name: 'Pizza')
Category.find_or_create_by(name: 'Polish')
Category.find_or_create_by(name: 'Pop-up Restaurants')
Category.find_or_create_by(name: 'Portuguese')
Category.find_or_create_by(name: 'Poutine')
Category.find_or_create_by(name: 'Pretzels')
Category.find_or_create_by(name: 'Russian')
Category.find_or_create_by(name: 'Salad')
Category.find_or_create_by(name: 'Sandwiches')
Category.find_or_create_by(name: 'Scandinavian')
Category.find_or_create_by(name: 'Scottish')
Category.find_or_create_by(name: 'Seafood')
Category.find_or_create_by(name: 'Shaved Ice')
Category.find_or_create_by(name: 'Shaved Snow')
Category.find_or_create_by(name: 'Singaporean')
Category.find_or_create_by(name: 'Slovakian')
Category.find_or_create_by(name: 'Smokehouses')
Category.find_or_create_by(name: 'Soul Food')
Category.find_or_create_by(name: 'Soup')
Category.find_or_create_by(name: 'Southern')
Category.find_or_create_by(name: 'Spanish')
Category.find_or_create_by(name: 'Sri Lankan')
Category.find_or_create_by(name: 'Steakhouses')
Category.find_or_create_by(name: 'Supper Clubs')
Category.find_or_create_by(name: 'Sushi Bars')
Category.find_or_create_by(name: 'Syrian')
Category.find_or_create_by(name: 'Taiwanese')
Category.find_or_create_by(name: 'Tapas')
Category.find_or_create_by(name: 'Tex-Mex')
Category.find_or_create_by(name: 'Thai')
Category.find_or_create_by(name: 'Turkish')
Category.find_or_create_by(name: 'Ukrainian')
Category.find_or_create_by(name: 'Vegan')
Category.find_or_create_by(name: 'Vegetarian')
Category.find_or_create_by(name: 'Vietnamese')
Category.find_or_create_by(name: 'Waffles')
Category.find_or_create_by(name: 'Wineries')
Category.find_or_create_by(name: 'Wraps')

african = Category.find_or_create_by(name: 'African')
african.children.find_or_create_by(name: 'Senegalese')
african.children.find_or_create_by(name: 'South African')

bars = Category.find_or_create_by(name: 'Bars')
bars.children.find_or_create_by(name: 'Airport Lounges')
bars.children.find_or_create_by(name: 'Beer Bars')
bars.children.find_or_create_by(name: 'Champagne Bars')
bars.children.find_or_create_by(name: 'Cocktail Bars')
bars.children.find_or_create_by(name: 'Dive Bars')
bars.children.find_or_create_by(name: 'Drive-Thru Bars')
bars.children.find_or_create_by(name: 'Gay Bars')
bars.children.find_or_create_by(name: 'Irish Pubs')
bars.children.find_or_create_by(name: 'Lounges')
bars.children.find_or_create_by(name: 'Pubs')
bars.children.find_or_create_by(name: 'Sake Bars')
bars.children.find_or_create_by(name: 'Speakeasies')
bars.children.find_or_create_by(name: 'Sports Bars')
bars.children.find_or_create_by(name: 'Tiki Bars')
bars.children.find_or_create_by(name: 'Vermouth Bars')
bars.children.find_or_create_by(name: 'Whiskey Bars')
bars.children.find_or_create_by(name: 'Wine Bars')

cafes = Category.find_or_create_by(name: 'Cafes')
cafes.children.find_or_create_by(name: 'Themed Cafes')

caribbean = Category.find_or_create_by(name: 'Caribbean')
caribbean.children.find_or_create_by(name: 'Dominican')
caribbean.children.find_or_create_by(name: 'Haitian')
caribbean.children.find_or_create_by(name: 'Puerto Rican')
caribbean.children.find_or_create_by(name: 'Trinidadian')

chinese = Category.find_or_create_by(name: 'Chinese')
chinese.children.find_or_create_by(name: 'Cantonese')
chinese.children.find_or_create_by(name: 'Dim Sum')
chinese.children.find_or_create_by(name: 'Hainan')
chinese.children.find_or_create_by(name: 'Shanghainese')
chinese.children.find_or_create_by(name: 'Szechuan')

french = Category.find_or_create_by(name: 'French')
french.children.find_or_create_by(name: 'Mauritius')
french.children.find_or_create_by(name: 'Reunion')

italian = Category.find_or_create_by(name: 'Italian')
italian.children.find_or_create_by(name: 'Calabrian')
italian.children.find_or_create_by(name: 'Sardinian')
italian.children.find_or_create_by(name: 'Sicilian')

japanese = Category.find_or_create_by(name: 'Japanese')
japanese.children.find_or_create_by(name: 'Conveyor Belt Sushi')
japanese.children.find_or_create_by(name: 'Donburi')
japanese.children.find_or_create_by(name: 'Izakaya')
japanese.children.find_or_create_by(name: 'Japanese Curry')
japanese.children.find_or_create_by(name: 'Kaiseki')
japanese.children.find_or_create_by(name: 'Okonomiyaki')
japanese.children.find_or_create_by(name: 'Onigiri')
japanese.children.find_or_create_by(name: 'Poke')
japanese.children.find_or_create_by(name: 'Ramen')
japanese.children.find_or_create_by(name: 'Sukiyaki')
japanese.children.find_or_create_by(name: 'Takoyaki')
japanese.children.find_or_create_by(name: 'Tempura')
japanese.children.find_or_create_by(name: 'Teppanyaki')
japanese.children.find_or_create_by(name: 'Tonkatsu')
japanese.children.find_or_create_by(name: 'Udon')
japanese.children.find_or_create_by(name: 'Yakiniku')
japanese.children.find_or_create_by(name: 'Yakitori')

latin_american = Category.find_or_create_by(name: 'Latin American')
latin_american.children.find_or_create_by(name: 'Colombian')
latin_american.children.find_or_create_by(name: 'Salvadoran')
latin_american.children.find_or_create_by(name: 'Venezuelan')

mediterranean = Category.find_or_create_by(name: 'Mediterranean')
mediterranean.children.find_or_create_by(name: 'Falafel')

middle_eastern = Category.find_or_create_by(name: 'Middle Eastern')
middle_eastern.children.find_or_create_by(name: 'Egyptian')
middle_eastern.children.find_or_create_by(name: 'Lebanese')
